### ISSUE TITLE
Capture (screenshot) Card List to populate card collection

### ISSUE THREAD

**Issue by adelpha** [MgAl2O4/FFTriadBuddy#20]
You're probably thinking about this already, but since in 5.4 we can now see ALL cards in the card list, including ones that haven't been collected, **and** they're arranged in strict numerical order, would you consider a feature where you can screen-capture the individual pages of the card list and auto-populate the player's card collection accordingly?

If not, would you at least put the card numbers in the List view so that manually adding cards to the collection is easier?

**Comment by MgAl2O4** [comment]
That was the entire point of Icons view. Not as good as automated screenshot reading, but still fast enough.
Plus, when you're going against NPC, you're usually already have it selected in NPC list, so it's just a matter of right clicking and selecting achieved rewards.

![image](https://user-images.githubusercontent.com/51430403/101485839-c49d0800-3929-11eb-8bb1-f0ebc8f06266.png)

Of course, it needs to be updated to match current card list fist. And maybe sorted differently.
The problem is, I'm currently taking a break from the game, so can't really check how things are changing. To update program, I'd need a help from someone who is playing - mostly with screenshots of game UI to analyze, but also with running built in data miner. It's annoying, but can't even update the game to do it myself without renewing subscription and it probably won't happen until next xpac.

If you (or anyone reading this) are interested in helping out, contact me on discord: IceWraith#1250
