### ISSUE TITLE
Feature request: better support for Three Open and All Open rules

### ISSUE THREAD

**Issue by Dreamwalk3r** [MgAl2O4/FFTriadBuddy#40]
Hello!
I'd like to suggest a support for "Open" rules, where before the game starts you could select cards you can see your opponent has, to shrink potential opponent card number.

**Comment by Dreamwalk3r** [comment]
Hello!
I'd like to suggest a support for "Open" rules, where before the game starts you could select cards you can see your opponent has, to shrink potential opponent card number.

**Comment by MgAl2O4** [comment]
This is for simulate mode, right? Screenshot based one should handle it already for solver purposes.

Won't it be more annoying to pick up to 5 (or 3) out of 10 before each game instead of just seeing all 10 on the list? I don't mind adding it, just trying to understand where exactly is the improvement of UX. 
In terms of time spent, having to select cards for all open will add... let's say 6s (1s each card + apply). Icons to click are rather small to (like in swap special rule UI) so it may be even longer to find matching image. 

I'm curious what's your view on this, haven't use simulate mode myself in a really long time :P

**Comment by Dreamwalk3r** [comment]
It's indeed for simulate, yeah, screenshot mode doesn't work for me (I probably should submit a bug report, right? =P)
Actually got the idea after losing 1 or 2 matches in the current Manderville tournament to Flichoirel, which probably could've been prevented either by me playing smarter or solver knowing which cards the opponent had x) Since tournament matches are limited, time spent isn't as important as getting a win.

**Comment by MgAl2O4** [comment]
I see. Makes sense, will do a pass on simulate and make it easier to work with.

Feel free to send another bug report on overlay mode not detecting game state, just remember about a screenshot to investigate issue on ;)

**Comment by MgAl2O4** [comment]
Updated in v68, made it skippable if someone prefers speed over visual clutter.
