### ISSUE TITLE
Please, make it bigger.

### ISSUE THREAD

**Issue by delolione** [MgAl2O4/FFTriadBuddy#43]
The cards in the simulation section are incredibly tiny and almost impossible to see on a 1920x1080 monitor unless you are very close to the screen. Please add a ui scaling option or card size option. 
![image](https://user-images.githubusercontent.com/28927294/123812343-9f69ea00-d8b9-11eb-8a21-86a581359948.png)

**Comment by MgAl2O4** [comment]
I assume you're talking about red deck & board cards, right?
A few questions to guide changes:

- how often are you selecting based on image alone?
- how often your deck (blue) is matching exact card order with tool?
- are numbers in single line format [up - left - down - right] easy enough to quickly identify card / match with what's happening on screen? (probably not)

**Comment by delolione** [comment]
1: constantly because play: screenshot has never worked for me and there are some visual discrepancies between the cards shown in the tool and the cards shown in game so you have to look hard sometimes which is very stressful with a very tiny image.
2: i never paid much attention to the order, sorry.
3: no... they are not. I have to lean in very close to read the numbers and sometimes the numbers blend in with the colors on the card making it harder.

**Comment by MgAl2O4** [comment]
Added new drawing mode in v72, real solution is complicated and time consuming, since tool's UI was never really meant to scale or do proper layouts. I'm slowly rewriting it on side, but it will take a a few weeks.

To use new mode:

1. run updated version
2. close it to update settings file with new value (it's saved on exit)
3. edit FFtriadBuddy-settings.json and change "bigUI":false  => "bigUI":true

Again, this is just temporary solution. 
Re overlay mode not working - send me a screenshot showing detection issue and i'll take a look.
