### ISSUE TITLE
Porting FFTriadBuddy to Dalamud as a plugin?

### ISSUE THREAD

**Issue by steponmepls** [MgAl2O4/FFTriadBuddy#67]
I don't think it has been addressed already but have you ever considered porting this program to [Dalamud](https://github.com/goatcorp/Dalamud)? [Other third party programs](https://github.com/LeonBlade/BurningDownTheHouse) made the jump to take advantage of the framework and I was wondering if you had plans to do the same or if you knew of its existence in the first place.

A totally [unrelated plugin](https://github.com/daemitus/MiniCactpotSolver) for Dalamud already fetches info from the game and draws on your screen to show you the most likely correct choices. In concept, it works similarly to FFTriadBuddy scan mode and considering the fact it fetches info from the game thanks to the framework maybe you could even skip the screenshot scanning you currently use to simply move to drawing green/yellow/red rectangles over the correct cards.

![image](https://user-images.githubusercontent.com/63500907/129045934-04618d4a-b550-4ab1-86fb-12170a263451.png)

**Comment by MgAl2O4** [comment]
Interesting, I didn't know they have so extensive insight into game's UI. Wasn't into doing reversing myself and went with image analysis as more resilient method (no surprise changes between releases, since stuff on screen looks the same)

Looking through (FFXIVClientStructs)[https://github.com/aers/FFXIVClientStructs/tree/main/FFXIVClientStructs/FFXIV/Client/UI] addons I don't see anything ready for triple triad minigame though, so eventual port still requires reversing game (easier with all existing work build by Dalamud's authors). I can give it a go, but can't promise anything - i'm rather bad at this stuff :D

**Comment by steponmepls** [comment]
It might require some additions to the API. I'm not sure of the specifics myself since I'm just a consuming user but maybe it's a discussion worth having with the dev team handling the API ( basically what you can or can't fetch from the game). Their [discord](https://discord.gg/3NMcUV5) is generally pretty quick in responding so if you are curious of new possibilities you should definitely check it out!

![image](https://user-images.githubusercontent.com/63500907/129055382-1b34acc8-45ac-44a4-b3d0-cf2e8389ff6d.png)

**Comment by MgAl2O4** [comment]
plugin repo: https://github.com/MgAl2O4/FFTriadBuddyDalamud

sent to testing, no idea how it goes from there, but should be available soonish as "TriadBuddy" plugin
