### ISSUE TITLE
Hardware acceleration

### ISSUE THREAD

**Issue by rad96** [MgAl2O4/FFTriadBuddy#68]
In last commit i see mention of Hardware Acceleration
Why it not working on my GPU? I don't see any spikes of GPU usage when Buddy is running, but i see CPU spike

![image](https://user-images.githubusercontent.com/2121715/129389239-55578831-d0c1-485d-b0ae-adf92e5ad52b.png)
![image](https://user-images.githubusercontent.com/2121715/129389265-ad91a89d-1ebc-4e86-abbe-f13efd78b782.png)

**Comment by MgAl2O4** [comment]
This option is meant to help with UI freezing under high GPU stress.
- disabled acceleration: UI rendering happens only on CPU, which means higher CPU usage
- not disabled = default state: UI rendering can utilize GPU, less CPU usage

Unless you run into UI freezing issue (#64 ), it's best to leave it unchecked.

I just verified that it does work as intended:
- checked (no GPU) = task manager never shows GPU when switching tabs / moving / causing updates
- unchecked (default) = task manager shows GPU when doing stuff above, no GPU shown when idling

(Task manager usage: bottom part of your image, rightmost column. Didn't really show anything in GPU charts, since it's just super simple drawing of batched UI)
