### ISSUE TITLE
hmm why?

### ISSUE THREAD

**Issue by DiggityMan420** [MgAl2O4/FFTriadBuddy#69]
see [Pic](https://imgshare.io/image/pJCGGO)

**Comment by MgAl2O4** [comment]
It's all good and by design :)

Each displayed deck has it's own solver providing win chance. Those are working independently and chances may slightly differ due to nature of used method, but as match progresses (and game space becomes smaller) accuracy of prediction will be going up.

Only synced solvers are deck optimizer and active player deck (requested in #60, see its comments for more details)
