### ISSUE TITLE
More then one Character save

### ISSUE THREAD

**Issue by DiggityMan420** [MgAl2O4/FFTriadBuddy#71]
It be nice if you save and switch on a character basis. as if I'm on one toon I can load or it auto-loads these setting and cards and if later on I was on a different toon I could load or it could auto-load based on my name a different setting and cards for that toon.

it takes a bit but you can sorta do it now with saving and loading just be nice to see a switch or see it load based on toon

**Comment by MgAl2O4** [comment]
Hm, I guess I can add this in a similar way that ui settings are handled.

In meantime, if you're playing on PC, check plugin version of this tool - should handle multiple characters automatically since it's reading all character specific data already (https://github.com/MgAl2O4/FFTriadBuddyDalamud)

**Comment by MgAl2O4** [comment]
Huh, apparently it's already done. Settings backup file includes owned cards, which is all you really need.
Info & Settings > Local saves on right side

**Comment by DiggityMan420** [comment]
ok cool and didnt know u made a plugin?
