### ISSUE TITLE
Possible to Make App Work with Larger-Scaled UI?

### ISSUE THREAD

**Issue by lwood999** [MgAl2O4/FFTriadBuddy#84]
I generally play with the UI scaled up to 150% (big monitor and bad eyes). 

Of course, this breaks the app, so I have to go into the settings, scale the UI back down to 100%, squint uncomfortably while I use it, then scale everything back up and do something else when the eyestrain gets to me.

Will this app ever be able to handle any of the other High Resolution UI Settings?

**Comment by MgAl2O4** [comment]
Hm, it's possible to make all screenshot reading work with any scale, but it's not trivial.
Scaling blurs pixels and makes all assumptions about their expected color values incorrect - in many different ways depending on scale. That's why I decided to avoid this group of issues rather than solve :D

How about checking XIVLauncher instead? -> https://goatcorp.github.io/
You can find a plugin version of this app there (TriadBuddy plugin) and it "integrates" with game UI much better - including UI scale support already :)
