### ISSUE TITLE
Some questions about the solver functionality

### ISSUE THREAD

**Issue by cdowen** [MgAl2O4/FFTriadBuddy#9]
Hello, your work is really impressive with the detailed data and rich functionality. I am trying to create a solver with reinforcement learning for the triad game and learn a lot from your tool. 
However, some issues still bother me. The complete strategy space for a pair of given decks is ~5million according to my calculation. But your program gives a result in a reasonable time even with deck composition included. I am wondering you are sampling rather than do a full search. If so, will increase the sampling frequency give a better winning chance? Are there any tips or tricks when implementing the solver?
Thanks for your work.

**Comment by MgAl2O4** [comment]
Yeah, doing full check is quite troublesome - that's why I'm not even trying to. I found that doing MCTS approach and testing X random games is quite good and accuracy increases as game progress allowing to salvage bad/not optimal moves from the beginning. On average, most games end up as win, which was good enough for my purpose. There's enough randomness in game itself to throw wrench into detailed plan, like Chaos rule or even sufficiently high number of unknown/uncertain cards in opponent deck.

I strongly suggest random exploration of graph as a baseline to prune number of moves to some manageable state. Optimization by not doing the actual work is best tip I have :D This was taken even further for deck optimizer functionality, where initial set of cards if filtered to just a few high star and low star pools instead of checking all possible combinations.

Solver itself can be further improved by switching to full check once number of possible moves is less  than X random games, or doing more levels of MCTS itself (I'm just limiting myself to first step and embracing chaos for all other moves :P ). 

At some point code itself can be a bottleneck, so it's always worth doing perf stats of various pieces to see where it can be improved. When it comes to millions of operations, even memory management can play important role.
